import express from 'express';
import { addExpenseController } from './user.controllers.js';
import { expenseSchema } from './user.validation.js';
import { validator } from '../auth/auth.validation.js';
import { asyncControllerHandler } from '../async-controller-handler.js';
import { authenticationMiddleware } from '../auth/auth-middleware.js';
import { getExpensesController } from './user.controllers.js';
import { deleteExpenseController } from './user.controllers.js';
import { editExpenseController } from './user.controllers.js';
import { dashboardController } from './user.controllers.js';
import { rankingsController } from './user.controllers.js';
import { archivesController } from './user.controllers.js';
import { restoreExpenseController } from './user.controllers.js';
import { updateMonthlyBudgetController } from './user.controllers.js';
import { thisMonthReportController } from './user.controllers.js';
export const userRoutes = express.Router();
userRoutes.post('/expenses', authenticationMiddleware, validator(expenseSchema), asyncControllerHandler(addExpenseController));
userRoutes.get('/expenses', authenticationMiddleware, asyncControllerHandler(getExpensesController));
userRoutes.delete('/expenses/:id', authenticationMiddleware, asyncControllerHandler(deleteExpenseController));
userRoutes.patch('/expenses/:id', authenticationMiddleware, validator(expenseSchema), asyncControllerHandler(editExpenseController));
userRoutes.get('/dashboard', authenticationMiddleware, asyncControllerHandler(dashboardController));
userRoutes.get('/rankings', authenticationMiddleware, asyncControllerHandler(rankingsController) );
userRoutes.get('/archives', authenticationMiddleware, asyncControllerHandler(archivesController) );
userRoutes.patch('/archives/:id', authenticationMiddleware, asyncControllerHandler(restoreExpenseController));
userRoutes.patch('/budget', authenticationMiddleware, asyncControllerHandler(updateMonthlyBudgetController));
userRoutes.get('/report', authenticationMiddleware, asyncControllerHandler(thisMonthReportController));
