import dotenv from 'dotenv';
dotenv.config();
import express from 'express';
import { addExpenseController } from './user.controllers.js';
import { expenseSchema } from './user.validation.js';
import { validator } from '../auth/auth.validation.js';
import { asyncControllerHandler } from '../async-controller-handler.js';
import { authenticationMiddleware } from '../auth/auth-middleware.js';
import { getExpensesController } from './user.controllers.js';
import { deleteExpenseController } from './user.controllers.js';
import { editExpenseController } from './user.controllers.js';
import { dashboardController } from './user.controllers.js';
import { rankingsController } from './user.controllers.js';
import { archivesController } from './user.controllers.js';
import { restoreExpenseController } from './user.controllers.js';
import { updateMonthlyBudgetController } from './user.controllers.js';
import { thisMonthReportController } from './user.controllers.js';
import { authorize } from '../authorization.js';
import { checkOrigin } from '../origin-checker-middleware.js';
import { expenseDayChartController } from './user.controllers.js';
export const userRoutes = express.Router();
//userRoutes.use(checkOrigin);
userRoutes.post('/expenses', authenticationMiddleware, authorize("user", "admin"), validator(expenseSchema), asyncControllerHandler(addExpenseController));
userRoutes.get('/expenses', authenticationMiddleware, authorize("user", "admin"),  asyncControllerHandler(getExpensesController));
userRoutes.delete('/expenses/:id', authenticationMiddleware, authorize("user", "admin"),  asyncControllerHandler(deleteExpenseController));
userRoutes.patch('/expenses/:id', authenticationMiddleware, authorize("user", "admin"),  validator(expenseSchema), asyncControllerHandler(editExpenseController));
userRoutes.get('/dashboard', authenticationMiddleware, authorize("user", "admin"),  asyncControllerHandler(dashboardController));
userRoutes.get('/rankings', authenticationMiddleware, authorize("user", "admin"),  asyncControllerHandler(rankingsController) );
userRoutes.get('/archives', authenticationMiddleware, authorize("user", "admin"),  asyncControllerHandler(archivesController) );
userRoutes.patch('/archives/:id', authenticationMiddleware, authorize("user", "admin"),  asyncControllerHandler(restoreExpenseController));
userRoutes.patch('/budget', authenticationMiddleware, authorize("user", "admin"),  asyncControllerHandler(updateMonthlyBudgetController));
userRoutes.get('/report', authenticationMiddleware, authorize("user", "admin"),  asyncControllerHandler(thisMonthReportController));
userRoutes.get('/days-chart', authenticationMiddleware, authorize("user", "admin"), asyncControllerHandler(expenseDayChartController));